plugins:
  - serverless-offline

service: tesletter-lambda-proxy

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

functions:
  cors-proxy:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: ''
          method: get
          cors: true
      - http:
          path: ''
          method: post
          cors: true
